want to play with vagrant and puppet but my local vbox install is busted. so lets just see what happens

diff --git a/deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb b/deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
--- a/deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
+++ b/deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
@@ -40,17 +40,29 @@ fi
 echo
 echo "------------------------------------------------------------------------" 
 
-# Run Python unit tests
-echo "Running python API client unit tests"
-env BMAPI_TEST_TYPE=vagrant_local python /buttonmen/test/tools/api-client/python/lib/test_bmapi.py
+# Run Python 2 unit tests
+echo "Running Python 2 API client unit tests"
+env BMAPI_TEST_TYPE=vagrant_local python /buttonmen/test/tools/python/api_client/test_bmapi.py
 if [ "$?" = "0" ]; then
   echo "Passed"
 else
   echo "FAILED: make sure this passes before committing code"
-  failed_tests="${failed_tests} test_api.py"
+  failed_tests="${failed_tests} test_bmapi.py"
 fi
 echo
-echo "------------------------------------------------------------------------" 
+echo "------------------------------------------------------------------------"
+
+# Run Python 3 unit tests
+echo "Running Python 3 API client unit tests"
+env BMAPI_TEST_TYPE=vagrant_local python3 /buttonmen/test/tools/python/api_client/test_bmapi.py
+if [ "$?" = "0" ]; then
+  echo "Passed"
+else
+  echo "FAILED: make sure this passes before committing code"
+  failed_tests="${failed_tests} test_bmapi.py"
+fi
+echo
+echo "------------------------------------------------------------------------"
 
 if [ "${failed_tests}" = "" ]; then
   echo "All checks passed"
